name: Sync
permissions: write-all

on:
  push:
    branches: [sync]
  pull_request:
    branches: [sync]

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      # - run: $env:WORKSPACE_ROOT=Get-Location
      - uses: actions/checkout@v3
        with:
          repository: QZLin/forward2
          ref: sync
          # path: forward2_sync
      - run: echo "::debug::$(ls -a)"
      - uses: actions/checkout@v3
        with:
          repository: QZLin/forward
          fetch-depth: 0
          path: forward
      - uses: actions/checkout@v3
        with:
          repository: QZLin/forward2
          fetch-depth: 0
          path: forward2
      - name: update
        run: |
          echo "::debug::$(Get-Location)"
          echo "::debug::$(ls -a)"
          pwsh ./update.ps1
